---
- name: Include directory task
  ansible.builtin.include_tasks: directory.yml

- name: Include package task
  ansible.builtin.include_tasks: package.yml

- name: Include download task
  ansible.builtin.include_tasks: download.yml

- name: Include configure task
  ansible.builtin.include_tasks: configure.yml
