---
name: Galaxy Import

on:
  push:
    branches: ["master"]

jobs:
  build:
    name: Galaxy Role Importer
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout git repo'
        uses: actions/checkout@v4

      - name: import to galaxy
        run: ansible-galaxy role import --token ${{ secrets.ANSIBLE_GALAXY_API_TOKEN }} ${{ github.repository_owner }} ${{ github.event.repository.name }}
